dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: cK+CLuXsYOXZVhhYL7aVgyGtLANp+UgIhiplZzcpmu6qapgkieu8Na06kOgDSnoAhlmtxFwh/qGYmV5HpEVEMk2auMkIlZXS5PDX+TNl5GwZxsxTfKS2n8g+6+olZOZ9aT1K7w2zQcvOTgkZEkEYmvU1111NPOEJOe9Qb6h0RpxPUzcLtN6f4s5xcb14u1PU4Ws3mNYHy/9a5XHFXllLG4BHaoXQetCx4dKQwB4GXtc6MRZGixnCu/2feb7u6QUSKv8wCer8LHMPg3UZJS8onQmxYKdZkuQw9xmpppJdXFzrGC2q9MRjJ6KU+TR4T5OmhbzkubjXKUSfQg0ZdMuLqCtwVa2iLpAYX8BXnxgtZOj6B5gaaWzMquaQ2Wa6deA50AZkHot7bBXzEyyEIf/ub9Jr92Pqc2KloTLnYpWzADiXfnZqD09zbkn6OxY/KxKQMUfzZFdFdILrX74PCWKD9CPVa/Kz2/hG3ReQmgFV2SVqlV6EZxOxWT9iHAFU4WpuP9Uvkau/R9dio9giCJ+A0CXYU1gJP6uASG5Nfz1csbZm6Nu05iAd81y3y99xHhCuBfIXAvohG1zieYn9OSm0sDEKBbjyIzUY0EAb5gqClJI3FpYPQpw2qD3mxQCpg98ZCeQ//vcq7xptAIhz00Foiusfh0y3AUm5NlDK/j8DvY8=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_max9744.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-max9744 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
